export const SITE = {
  name: "VaultScaler",
  product: "Radix Core",
  url: "https://vaultscaler.com",
  email: "ian@vaultscaler.com",
  launchISO: "2025-11-15",
  description:
    "Get 21% more throughput from your training GPUs in 60 seconds. Radix solves the hidden GPU scheduling problem with real-time multi-dimensional optimization.",
  keywords: [
    "Kubernetes GPU",
    "offline dashboard",
    "zero egress",
    "air-gapped",
    "read-only observer",
    "Helm chart",
    "GPU observability",
    "Kubernetes monitoring",
    "GPU cluster management",
    "AI infrastructure",
    "ML ops",
    "data center GPU",
    "cluster observability",
    "zero-egress monitoring",
    "air-gapped Kubernetes",
    "GPU workload scheduling",
    "Kubernetes operator",
    "infrastructure as code",
    "DevOps GPU",
    "AI platform engineering",
  ],
};
