export const SITE = {
  name: "VaultScaler",
  products: ["Radix Core", "Radix Studio"],
  url: "https://vaultscaler.com",
  email: "bpruess@vaultscaler.com",
  launchISO: "2026-03-02",
  description:
    "VaultScaler harmonizes AI operations at scale. Radix Core gives you GPU cost savings and governance policies for model training. Radix Studio gives you visibility, standardization and governance for every LLM call so you can deploy with confidence.",
  keywords: [
    // Pain point keywords (what people search when frustrated)
    "reduce GPU costs",
    "GPU underutilization",
    "AI governance tools",
    "LLM cost control",
    "AI compliance platform",
    "GPU wastage",
    "training throughput optimization",
    "AI ops automation",
    "LLM vendor lock-in",
    "GPU scheduling efficiency",
    "model training optimization",
    "AI infrastructure cost reduction",
    // Solution keywords
    "GPU optimizer",
    "AI operations platform",
    "LLM governance platform",
    "GPU scheduler",
    "AI pipeline orchestration",
    "multi-cloud AI platform",
    "LLM orchestration",
    "AI cost optimization",
    // Technical keywords
    "Kubernetes GPU scheduling",
    "Slurm GPU optimization",
    "MLOps platform",
    "AIOps platform",
    "GPU cluster optimization",
    "AI workload management",
  ],
};
